exports.adminmessage = {
  emailnotexist: 'Email does not exist.',
  count: 'Count added successfully.',
  countalready: 'Data already added.',
  loginsuccessfully: 'Login successfully.',
  profile: 'Please complete profile.',
  veriaccount: 'Verify your account.',
  wrongpassword: 'Email and password are invalid.',
  mailsent: 'Password reset link sent to your email account.',
  verifymailsent: 'Verify mail sent to your email account.',
  otpnotverify: 'Otp Verify Unsuccessfully.',
  passwordsuccessfully: 'Password change successfully.',
  oldpasswordsame: 'The new password is the same as the old password.',
  profileget: 'Profile get successfully.',
  usernotfound: 'User not found.',
  profileupdate: 'Profile updated successfully.',
  modelupdate: 'Model updated successfully.',
  modelnotfound: 'Model not found.',
  modeldelete: 'Model deleted successfully.',
  cmsget: 'CMS get succeessfully.',
  termsget: 'Terms and condition get successfully.',
  privacyget: 'Cms get succeessfully.',
  contactadmin: 'Contact admin form filled successfully.',
  cmsnotfound: 'CMS not found.',
  cmsupdate: 'CMS updated successfully.',
  newsimage: 'Please enter news image.',
  newsadd: 'News added successfully.',
  newsget: 'News get successfully.',
  newslist: 'News not found.',
  newsnotfound: 'News not found.',
  newsupdate: 'News updated successfully.',
  newsdelete: 'News deleted successfully.',
  agentnotfound: 'Agent not found.',
  agentupdate: 'Agent updated successfully.',
  agentdelete: 'Agent deleted successfully.',
  resourceupdate: 'Resource updated successfully.',
  resourcenotfound: 'Resource not found.',
  resourcedelete: 'Resource deleted successfully.',
  reportdata: 'Report data get successfully.',
  dashboarddata: 'Dashboard data get successfully.',
  resourcestep: 'Resource setup complete.',
  resourceapprove: 'Resource approve successfully.',
  modelapprove: 'Model approve successfully.',
  agentapprove: 'Agent approve successfully.',
  resourcereject: 'Resource reject successfully.',
  modelreject: 'Model reject successfully.',
  agentreject: 'Agent reject successfully.',
  datanot: 'Data not found.',
  requestpending: 'Your request is pending.',
  requestaccept: 'Your request is already accepted.',
  requestdecline: 'Your request is declined.',
  limit: 'Limit exceed.',
  requestsend: 'Request send successfully.',
  dataget: 'Data get successfully.'
};

exports.usermessage = {
  accountApproval:"Account awaiting approval!",
  imagedelete: 'Image deleted successfully.',
  agentsignup:'User signup successfully',
  emailexist: 'Account is already exist with same email',
  modelexist: 'Account is already exist with same email as model.',
  agentexist: 'Account is already exist with same email as agent.',
  resourceexist: 'Account is already exist with same email as resource.',
  agentpersonalinformation: 'Your personal information added successfully.',
  agentpersonalinformationupdated: 'Your personal information updated successfully.',
  agentpersonalinformationget: 'Your personal information get successfully.',
  agentcompanyinformationadd: 'Your company information added successfully.',
  agentcompanyinformationedit: 'Your company information updated successfully.',
  agentcompanyinformationget: 'Your company information get successfully.',
  agentinterestget: 'Agent interest get successfully.',
  agentcompanyinformationdatanotfound: 'Your company information not found.',
  agentcompanydocumentadd: 'Your company document added successfully.',
  agentcompanydocumentedit: 'Your company document updated successfully.',
  passwordaddedsuccessfully: 'Your password created successfully.',
  datanotfound: "Missing input parameter.",
  agentinterestadd: 'Your interest added successfully.',
  agentinterestedit: 'Your interest updated successfully.',
  bodyappereanceedit: 'Your body appereance updated successfully.',
  bodyappereanceadd: 'Your body appereance added successfully.',
  bodyappereanceget: 'Your body appereance get successfully.',
  bodyappereancenotfound: 'Your body appereance not found.',
  bodymeasurmentedit: 'Your body measurment updated successfully.',
  bodymeasurmentadd: 'Your body measurment added successfully.',
  bodymeasurmentget: 'Your body measurment get successfully.',
  bodymeasurmentnotfound: 'Your body measurment not found.',
  digitaledit: 'Your digital updated successfully.',
  digitaladd: 'Your digital added successfully.',
  digitalget: 'Your digital get successfully.',
  digitalnotfound: 'Your digital not found.',
  bookedit: 'Your books updated successfully.',
  bookadd: 'Your books added successfully.',
  bookget: 'Your books get successfully.',
  booknotfound: 'Your books not found.',
  socialedit: 'Your social link updated successfully.',
  socialadd: 'Your social link added successfully.',
  socialget: 'Your social link get successfully.',
  socialnotfound: 'Your social link not found.',
  placementedit: 'Your placement updated successfully.',
  placementadd: 'Your placement added successfully.',
  placementget: 'Your placement get successfully.',
  placementnotfound: 'Your placement not found.',
  countryget: 'Country get successfully.',
  agentcountryedit: 'Agent Country updated successfully.',
  agentcountryadd: 'Agent Country added successfully.',
  availablecountryget: 'Available country get successfully.',
  changePasswordUpdate: 'Change Password Successfully.',
  invalidPCredentials: 'Old Password is wrong.',
  samepassword: 'Old password and new password should not be same.',
  invalidUserId: 'User not found.',
  modellistget: 'Model list get succeessfully.',
  modelupdate: 'Model updated successfully.',
  modelget: 'Model get succeessfully.',
  Agentget: 'Agent get succeessfully.',
  resourceadd: 'Resource added successfully.',
  resourcelistget: 'Resource list get succeessfully.',
  resourceget: 'Resource get succeessfully.',
  exploreget: "Explore get successfully.",
  exploreget: "Activity get successfully.",
  search: 'Search get succeessfully.',
  activitydelete: 'Activity delete succeessfully.',
  subscriptionSuccess: 'Subscription succeessfully',
  logoutsuccess: 'Logout Successfully.',
  fcmupdate: 'Token updated successfully.',
  SignupUser:"Signup Users fetched Successfully"
};
exports.statuscode = {
 success:200,
 bad_request:400,
 unauthorized:401,
 forbidden:403,
 not_found:404,
};